export type EventType = RundownEventType | IngestEventType

export enum RundownEventType {
  ACTIVATED = 'ACTIVATED',
  DEACTIVATED = 'DEACTIVATED',
  DELETED = 'DELETED',
  RESET = 'RESET',
  TAKEN = 'TAKEN',
  SET_NEXT = 'SET_NEXT',
  PART_INSERTED_AS_ON_AIR = 'PART_INSERTED_AS_ON_AIR',
  PART_INSERTED_AS_NEXT = 'PART_INSERTED_AS_NEXT',
  PIECE_INSERTED = 'PIECE_INSERTED',
  AD_LIB_PIECE_INSERTED = 'AD_LIB_PIECE_INSERTED',
  INFINITE_PIECE_ADDED = 'INFINITE_PIECE_ADDED'
}

export enum IngestEventType {
  SEGMENT_CREATED = 'SEGMENT_CREATED',
  SEGMENT_DELETED = 'SEGMENT_DELETED'
}
