export enum PieceType {
  UNKNOWN = 'UNKNOWN',
  CAMERA = 'CAMERA',
  LIVE = 'LIVE',
  GRAPHIC = 'GRAPHIC',
  SERVER = 'SERVER',
  AUDIO = 'AUDIO',
  TRANSITION = 'TRANSITION',
  VIDEO_SWITCHER = 'VIDEO_SWITCHER'
  // Add as needed
}
