export enum PieceAvailabilityStatus {
  UNKNOWN = 'UNKNOWN',
  OK = 'OK',
  SOURCE_HAS_ISSUES = 'SOURCE_HAS_ISSUES',
  SOURCE_BROKEN = 'SOURCE_BROKEN',
  SOURCE_MISSING = 'SOURCE_MISSING',
  SOURCE_NOT_SET = 'SOURCE_NOT_SET',
}
