export enum RundownEventType {
  ACTIVATED = 'ACTIVATED',
  DEACTIVATED = 'DEACTIVATED',
  DELETED = 'DELETED',
  RESET = 'RESET',
  TAKEN = 'TAKEN',
  SET_NEXT = 'SET_NEXT',
  AD_LIB_PIECE_INSERTED = 'AD_LIB_PIECE_INSERTED',
  INFINITE_PIECE_ADDED = 'INFINITE_PIECE_ADDED'
}
