export enum SetNextDirection {
  SEGMENT_BEFORE_NEXT_SEGMENT = 'SEGMENT_BEFORE_NEXT_SEGMENT',
  SEGMENT_AFTER_NEXT_SEGMENT = 'SEGMENT_AFTER_NEXT_SEGMENT',
  PART_BEFORE_NEXT_PART = 'PART_BEFORE_NEXT_PART',
  PART_AFTER_NEXT_PART = 'PART_AFTER_NEXT_PART'
}
