services:
  server-core:
    image: 'tv2media/sofie-server-core:v46.3.4-staging'
    platform: 'linux/amd64'
    container_name: 'server-core'
    ports:
      - '3000:80'
    volumes:
      - '${PWD}/coredisk:/opt/coredisk'
      - '${PWD}/core-settings.json:/opt/core-settings.json:ro'
    restart: 'always'
    environment:
      TZ: '${TZ:-Europe/Copenhagen}'
      MONGO_URL: 'mongodb://host.docker.internal:3001/meteor?directConnection=true'
      MONGO_OPLOG_URL: 'mongodb://host.docker.internal:3001/local?directConnection=true'
      ROOT_URL: 'http://localhost:3000'
      PORT: '80'
      NODE_ENV: 'local'
      LOG_LEVEL: 'debug'

  playout-gateway:
    image: 'tv2media/sofie-playout-gateway:v46.3.4-staging'
    platform: 'linux/amd64'
    container_name: 'playout-gateway'
    restart: 'always'
    environment:
      TZ: '${TZ:-Europe/Copenhagen}'
      CORE_HOST: 'server-core'
      CORE_PORT: '80'
      DEVICE_ID: 'playout-gateway-localhost'
      DEVICE_TOKEN: 'playout-gateway-token'
      NODE_ENV: 'local'
      LOG_LEVEL: 'debug'

  inews-gateway:
    image: 'tv2media/inews-ftp-gateway:46.3.2-staging'
    platform: 'linux/amd64'
    container_name: 'inews-gateway'
    restart: 'always'
    ports:
      - '3007:3007'
    environment:
      TZ: '${TZ:-Europe/Copenhagen}'
      CORE_HOST: 'server-core'
      CORE_PORT: '80'
      DEVICE_ID: 'inews-gateway-localhost'
      DEVICE_TOKEN: 'inews-gateway-token'
      NODE_ENV: 'local'
      LOG_LEVEL: 'debug'
