export type EventType = RundownEventType | IngestEventType | ActionTriggerEventType

export enum RundownEventType {
  ACTIVATED = 'ACTIVATED',
  DEACTIVATED = 'DEACTIVATED',
  RESET = 'RESET',
  TAKEN = 'TAKEN',
  SET_NEXT = 'SET_NEXT',
  PART_INSERTED_AS_ON_AIR = 'PART_INSERTED_AS_ON_AIR',
  PART_INSERTED_AS_NEXT = 'PART_INSERTED_AS_NEXT',
  PIECE_INSERTED = 'PIECE_INSERTED',
  INFINITE_PIECE_ADDED = 'INFINITE_PIECE_ADDED'
}

export enum IngestEventType {
  RUNDOWN_CREATED = 'RUNDOWN_CREATED',
  RUNDOWN_UPDATED = 'RUNDOWN_UPDATED',
  RUNDOWN_DELETED = 'RUNDOWN_DELETED',
  SEGMENT_CREATED = 'SEGMENT_CREATED',
  SEGMENT_UPDATED = 'SEGMENT_UPDATED',
  SEGMENT_DELETED = 'SEGMENT_DELETED',
  PART_CREATED = 'PART_CREATED',
  PART_UPDATED = 'PART_UPDATED',
  PART_DELETED = 'PART_DELETED'
}

export enum ActionTriggerEventType {
  ACTION_TRIGGER_CREATED = 'ACTION_TRIGGER_CREATED',
  ACTION_TRIGGER_UPDATED = 'ACTION_TRIGGER_UPDATED',
  ACTION_TRIGGER_DELETED = 'ACTION_TRIGGER_DELETED'
}
