export enum Tv2OutputLayer {
  PROGRAM = 'PROGRAM',
  SECONDARY = 'SECONDARY',
  JINGLE = 'JINGLE',
  OVERLAY = 'OVERLAY',
  AUXILIARY = 'AUXILIARY',
  MANUS = 'MANUS',
  AUDIO = 'AUDIO',
  NONE = 'NONE'
}
