name: 'Check'
run-name: 'Test, build, lint and validate'

on:
  pull_request:
  push:
    branches: [main]

jobs:
  status:
    uses: 'tv2/ag-github-actions/.github/workflows/status-check.yml@v2'
    with:
      node-version: '24.11'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}