name: Scheduled Merge Master -> Staging -> Develop

on:
  schedule:
    - cron: '0 0 * * 1-5' # At 00:00, Monday through Friday
  workflow_dispatch: # on button click

jobs:
  merge-master-to-staging:
    name: Create merge PR for Master to Staging
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set Git config
          run: |
            git config --local user.email "Sofie-Automation@users.noreply.github.com"
            git config --local user.name "GitHub Actions # Sofie-Automation"
        - name: Create Merge Pull Request - 'master' to 'staging'
          uses: repo-sync/pull-request@v2
          with:
            source_branch: master
            destination_branch: staging
            pr_title: Merge 'master' -> 'staging'
            pr_body: |
              Branch 'main' has changes not on 'staging' branch.
              Merging this pull request will apply the changes to the 'staging' branch.
            github_token: ${{ secrets.GITHUB_TOKEN }}

  merge-staging-to-develop:
    name: Create merge PR for Staging to Develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "Sofie-Automation@users.noreply.github.com"
          git config --local user.name "GitHub Actions # Sofie-Automation"
      - name: Create Merge Pull Request - 'staging' to 'develop'
        uses: repo-sync/pull-request@v2
        with:
          source_branch: staging
          destination_branch: develop
          pr_title: Merge 'staging' -> 'develop'
          pr_body: |
            Branch 'staging' has changes not on 'develop' branch.
            Merging this pull request will apply the changes to the 'develop' branch.
          github_token: ${{ secrets.GITHUB_TOKEN }}